# Generated by Django 5.1.15 on 2026-04-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='admin', max_length=50, unique=True),
        ),
    ]
