# Generated by Django 5.1.15 on 2026-04-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_color_user_pin_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_pin_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('stock_clerk', 'Stock Clerk')], default='cashier', max_length=20),
        ),
    ]
