# Generated by Django 6.0.2 on 2026-05-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polineitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
