# Generated by Django 6.0.2 on 2026-04-22 10:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('physical_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='AuditSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('all', 'All Stock'), ('category', 'Category'), ('subcategory', 'Sub-Category')], default='all', max_length=15)),
                ('sample_size', models.IntegerField(default=10)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
