# Generated by Django 5.1.15 on 2026-05-21 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_module', '0002_initial'),
        ('payroll', '0005_remove_payrollentry_reward_points_redeemed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audititem',
            name='action_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('disputed', 'Disputed'), ('posted', 'Posted')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='audititem',
            name='payroll_adjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_items', to='payroll.payrolladjustment'),
        ),
        migrations.AddField(
            model_name='audititem',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audititem',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_audit_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
