# Generated by Django 5.1.15 on 2026-05-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_module', '0003_audititem_action_status_audititem_payroll_adjustment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audititem',
            name='action_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('validated', 'Validated'), ('disputed', 'Disputed'), ('posted', 'Posted')], default='pending', max_length=15),
        ),
    ]
