# Generated by Django 6.0.2 on 2026-04-22 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('sale_processed', 'Sale Processed'), ('sale_voided', 'Sale Voided / Refund'), ('price_changed', 'Product Price Changed'), ('stock_adjusted', 'Stock Adjusted (Manual)'), ('po_created', 'PO Created'), ('po_approved', 'PO Approved'), ('goods_received', 'Goods Received'), ('promotion_changed', 'Promotion Created / Edited / Deleted'), ('hamper_changed', 'Hamper Created / Edited'), ('audit_completed', 'Stock Audit Completed'), ('user_changed', 'User Created / Role Changed'), ('login', 'Login'), ('logout', 'Logout')], max_length=30)),
                ('entity_type', models.CharField(blank=True, default='', max_length=50)),
                ('entity_id', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Trail Entry',
                'verbose_name_plural': 'Audit Trail',
                'ordering': ['-created_at'],
            },
        ),
    ]
