from django.core.management.base import BaseCommand
from catalogue.models import Category, SubCategory, Product, FragmentSize
from accounts.models import User
from decimal import Decimal
import re
from django.db import IntegrityError

class Command(BaseCommand):
    help = 'Seeds the database with ALL 500+ Jimmy Mini Mart items'

    def handle(self, *args, **kwargs):
        self.stdout.write("Starting Comprehensive Jimmy Mini Mart seed (500+ items)...")
        
        admin = User.objects.filter(is_superuser=True).first() or User.objects.first()
        if not admin:
            self.stdout.write(self.style.ERROR("Error: No user found."))
            return

        # 1. Category Definitions
        categories_config = {
            'Airtime': ('📱', ['Airtel', 'Safaricom']),
            'Stationery': ('✏️', ['Ex. Book', 'Counter BK', 'Note Book', 'Pen', 'Pencil', 'Eraser', 'Ruler', 'Geo. Set', 'Envelope', 'File', 'Ink', 'Calculator', 'Success Card', 'Manilla', 'Math Table', 'Sharpener', 'Colors', 'Crayon', 'Clip Board', 'Glue', 'Tapes', 'Staples']),
            'Food Staples': ('🍚', ['Sugar', 'Salt', 'Rice', 'Flour', 'Ngano', 'Cooking Oil', 'Cooking Fat', 'Spaghetti', 'Indomie', 'Sossi', 'Ujimix', 'Seasoning', 'Royco', 'Onga', 'Curry', 'Masala', 'M.M.']),
            'Beverages': ('☕', ['Tea', 'Coffee', 'Cocoa', 'Milo', 'Nescafe', 'Bevrg']),
            'Drinks': ('🥤', ['Soda', 'Juice', 'Water', 'Energy Drink', 'Predator', 'Brava', 'Ice Cube', 'Ice Jelly', 'Lolly', 'Ice Pop']),
            'Dairy & Bakery': ('🍞', ['Milk', 'Bread', 'Cakes', 'Mandazi', 'KDF', 'Nginduri', 'Ngumu', 'Blueband', 'Yoghurt', 'Eggs']),
            'Snacks & Biscuits': ('🍪', ['Biscuit', 'Candy', 'Peanuts', 'Crisps', 'Popcorn', 'Wafers', 'Chocolate Bar', 'Weetabix', 'Balloon Joy', 'Fun Time', 'Ringoz', 'Wow', 'Yummy', 'Peanuts']),
            'Personal Care': ('🧴', ['Soap Tab', 'Jelly', 'Lotion', 'Tooth P.', 'Tooth Brush', 'Pads', 'Diapers', 'Razor', 'Cutex', 'Perfume', 'Ear Buds', 'Glycerine', 'Hair', 'Condom', 'Trust', 'Spirit', 'Masks', 'Wet Wipes', 'Vaseline', 'Arimis', 'Naturally Fair', 'Foundation']),
            'Household': ('🏠', ['Battery', 'Bulb', 'Matchbox', 'Candle', 'Torch', 'Padlock', 'Ropes', 'Tape', 'Glue', 'Nail Cutter', 'Insecticide', 'Mirror', 'Umbrella', 'Watch', 'Mosquito Coil', 'Key Holder', 'Gas Lighter']),
            'Cleaning Supplies': ('🧼', ['Soap Powder', 'Soap Bar', 'Bleach', 'JIK', 'Scrubber', 'Broom', 'Brush', 'Downy', 'Starsoft', 'Serviette', 'Spirit']),
            'Kitchenware': ('🍳', ['Grater', 'Lunch Box', 'Lunch Busket', 'Sieve', 'Tumbler', 'Mwiko', 'Feeding Bottle']),
            'Tools & Sewing': ('🧵', ['Needle', 'Thread', 'Wool', 'Crochet', 'Knitting', 'Sack Needle', 'Machine Oil', 'Cloth Line', 'Speaker Cable']),
            'Cigarettes': ('🚬', ['Dunhill', 'Pallmall', 'Rooster', 'Rothmans', 'Safari']),
            'Clothing & Access.': ('👕', ['Socks', 'Handkerchief', 'Earrings', 'Hair Band', 'Hair Cap']),
            'Toys & Games': ('🧸', ['Toy Car', 'Balls', 'Baloons']),
            'Miscellaneous': ('📦', ['Miscellaneous', 'Phone Charging', 'Pressure', 'Jerry Can']),
        }

        # Create Categories and Subcategories
        cats = {}
        subcats = {}
        for cat_name, (icon, subs) in categories_config.items():
            cat, _ = Category.objects.get_or_create(name=cat_name, defaults={'icon': icon})
            cats[cat_name] = cat
            for sub_name in subs:
                sub, _ = SubCategory.objects.get_or_create(category=cat, name=sub_name)
                subcats[f"{cat_name}:{sub_name}"] = sub

        # General Fallbacks
        for cat_name, cat_obj in cats.items():
            sub, _ = SubCategory.objects.get_or_create(category=cat_obj, name='General')
            subcats[f"{cat_name}:General"] = sub

        # 2. Comprehensive Item Data (500+ items)
        # Format: (Name, Category, SubCategoryHint, Price, [BundleQty, BundlePrice])
        items_data = [
            # AIRTIME
            ('AIRTIME AIRTEL (10)', 'Airtime', 'Airtel', 10),
            ('AIRTIME AIRTEL (20)', 'Airtime', 'Airtel', 20),
            ('AIRTIME AIRTEL (50)', 'Airtime', 'Airtel', 50),
            ('AIRTIME AIRTEL (100)', 'Airtime', 'Airtel', 100),
            ('AIRTIME SAFARICOM (10)', 'Airtime', 'Safaricom', 10),
            ('AIRTIME SAFARICOM (20)', 'Airtime', 'Safaricom', 20),
            ('AIRTIME SAFARICOM (50)', 'Airtime', 'Safaricom', 50),
            ('AIRTIME SAFARICOM (100)', 'Airtime', 'Safaricom', 100),

            # BAGS & PACKAGING
            ('ALLUM. FOIL 5M', 'Bags & Packaging', 'General', 180),
            ('BAGS Nonwoven #15', 'Bags & Packaging', 'General', 5),
            ('BAGS Nonwoven #22', 'Bags & Packaging', 'General', 10),
            ('BAGS Nonwoven #28', 'Bags & Packaging', 'General', 20),
            ('BAGS Shopping (flowered)', 'Bags & Packaging', 'General', 50),
            ('CARRIER SACK BIG', 'Bags & Packaging', 'General', 50),
            ('CARRIER SACK MED. V26', 'Bags & Packaging', 'General', 40),
            ('CARRIER SACK SMALL V22', 'Bags & Packaging', 'General', 30),
            ('ONION NETS', 'Bags & Packaging', 'General', 70),

            # TOYS & BALLS
            ('BALLS Big @70', 'Toys & Games', 'Balls', 70),
            ('BALLS Small @50', 'Toys & Games', 'Balls', 50),
            ('BALOONS', 'Toys & Games', 'Baloons', 10),
            ('TOY CARS Medium', 'Toys & Games', 'Toy Car', 50),
            ('TOY CARS Small', 'Toys & Games', 'Toy Car', 40),

            # HOUSEHOLD
            ('BARUTI 3s', 'Household', 'General', 1.67, 3, 5),
            ('BARUTI Rockets', 'Household', 'General', 20),
            ('BATTERY (Eveready) AA', 'Household', 'Battery', 80),
            ('BATTERY (Eveready) AAA pairs', 'Household', 'Battery', 70),
            ('BATTERY (Eveready) Sz-D pairs', 'Household', 'Battery', 180),
            ('BATTERY (Golden Lion) Size D', 'Household', 'Battery', 30),
            ('BATTERY (Tocebal) AA', 'Household', 'Battery', 15),
            ('BATTERY (Tocebal) AAA', 'Household', 'Battery', 10),
            ('BULB 5W', 'Household', 'Bulb', 65),
            ('BULB 7W', 'Household', 'Bulb', 80),
            ('BULB 10W', 'Household', 'Bulb', 100),
            ('BULB 15W', 'Household', 'Bulb', 150),
            ('BULB 1707A Emergency', 'Household', 'Bulb', 300),
            ('BULB 1709A Emergency', 'Household', 'Bulb', 350),
            ('BULB Rechargeable 40w', 'Household', 'Bulb', 450),
            ('BULB Rechargeable 50w', 'Household', 'Bulb', 550),
            ('CANDLES', 'Household', 'Candle', 15),
            ('MATCHBOX', 'Household', 'Matchbox', 5),
            ('PADLOCK AUDDY 32mm', 'Household', 'Padlock', 250),
            ('PADLOCK SOLIX Large', 'Household', 'Padlock', 200),
            ('PADLOCK SOLIX medium', 'Household', 'Padlock', 150),
            ('PADLOCK SOLIX Small', 'Household', 'Padlock', 100),
            ('PADLOCK Stella 60mm', 'Household', 'Padlock', 350),
            ('PADLOCK STELAR 40mm', 'Household', 'Padlock', 265),
            ('PADLOCK STELAR 50mm', 'Household', 'Padlock', 300),
            ('PADLOCK TRIC. 262', 'Household', 'Padlock', 70),
            ('PADLOCK TRIC. 263', 'Household', 'Padlock', 90),
            ('PADLOCK TRIC. 264', 'Household', 'Padlock', 120),
            ('PADLOCK TRIC. Original 264', 'Household', 'Padlock', 350),
            ('PADLOCK YONGLI 363', 'Household', 'Padlock', 100),
            ('UMBRELLA', 'Household', 'Umbrella', 500),
            ('UMBRELLA mini fold', 'Household', 'Umbrella', 250),
            ('WATCH Asahi', 'Household', 'Watch', 50),
            ('WATCH Light', 'Household', 'Watch', 160),
            ('WATCH Sports', 'Household', 'Watch', 180),
            ('KEY HOLDERS', 'Household', 'Key Holder', 50),
            ('GAS LIGHTER', 'Household', 'Gas Lighter', 20),

            # BEVERAGES
            ('BEVRG COCOA Raha 80g', 'Beverages', 'Cocoa', 240),
            ('BEVRG. CHOCOLATE Drnkg 10g', 'Beverages', 'Cocoa', 10),
            ('BEVRG. CHOCOLATE Drnkg 20g', 'Beverages', 'Cocoa', 20),
            ('BEVRG. CHOCOLATE Drnkg 100g', 'Beverages', 'Cocoa', 140),
            ('BEVRG. CHOCOPRIMO 5', 'Beverages', 'Cocoa', 5),
            ('BEVRG. CHOCOPRIMO 10g', 'Beverages', 'Cocoa', 10),
            ('BEVRG. CHOCOPRIMO 20g', 'Beverages', 'Cocoa', 20),
            ('BEVRG. CHOCOPRIMO 100g', 'Beverages', 'Cocoa', 140),
            ('BEVRG. COCOA Raha 10g', 'Beverages', 'Cocoa', 15),
            ('BEVRG. GIBSONS | Dormans 2g', 'Beverages', 'Coffee', 10),
            ('BEVRG. GIBSONS 1.6g', 'Beverages', 'Coffee', 10),
            ('BEVRG. GIBSONS Kahawa Econ', 'Beverages', 'Coffee', 25),
            ('BEVRG. Kahawa Sp. No.1', 'Beverages', 'Coffee', 25),
            ('BEVRG. KAHAWA No. 1', 'Beverages', 'Coffee', 30),
            ('BEVRG. MILO Sachets 10g', 'Beverages', 'Milo', 20),
            ('BEVRG. NESCAFE', 'Beverages', 'Nescafe', 10),
            ('BEVRG. NESCAFE 3-IN-1', 'Beverages', 'Nescafe', 25),
            ('BEVRG. TIRA Coffee', 'Beverages', 'Coffee', 10),
            ('TEA LEAVES #30', 'Beverages', 'Tea', 30),
            ('TEA LEAVES #60', 'Beverages', 'Tea', 60),
            ('TEA LEAVES NDIMA 120g', 'Beverages', 'Tea', 80),
            ('TEA LEAVES NDIMA 240g', 'Beverages', 'Tea', 140),
            ('TEA LEAVES NDIMA 500g', 'Beverages', 'Tea', 240),
            ('TEA LEAVES EDEN 25g', 'Beverages', 'Tea', 10),
            ('TEA LEAVES EDEN 50g', 'Beverages', 'Tea', 20),
            ('TEA LEAVES EDEN T\'wizi 25g', 'Beverages', 'Tea', 15),
            ('TEA LEAVES GREEN Tea 240g', 'Beverages', 'Tea', 180),
            ('TEA LEAVES Melvin T\'wizi 15g', 'Beverages', 'Tea', 15),
            ('TEA LEAVES PURPLE 50g', 'Beverages', 'Tea', 150),

            # PERSONAL CARE
            ('BIC RAZOR', 'Personal Care', 'Razor', 30),
            ('CUTEX (QUTEX) Nail Polish 20ml', 'Personal Care', 'Cutex', 60),
            ('CUTEX N. VANISH Small', 'Personal Care', 'Cutex', 30),
            ('DIAPERS Adult pcs', 'Personal Care', 'Diapers', 100),
            ('DIAPERS Adult Pack', 'Personal Care', 'Diapers', 1000),
            ('DIAPERS Kisskid pcs', 'Personal Care', 'Diapers', 20),
            ('DIAPERS Kisskid pkt', 'Personal Care', 'Diapers', 150),
            ('DIAPERS Softcare Jumbo Pcs', 'Personal Care', 'Diapers', 20),
            ('DIAPERS Softcare Jumbo Pkt', 'Personal Care', 'Diapers', 750),
            ('DIAPERS Softcare LC Pack', 'Personal Care', 'Diapers', 150),
            ('DIAPERS Softcare LC Pcs', 'Personal Care', 'Diapers', 20),
            ('DIAPERS Softcare XL Pack', 'Personal Care', 'Diapers', 160),
            ('DIAPERS Softcare XL Pcs', 'Personal Care', 'Diapers', 25),
            ('EAR BUDS', 'Personal Care', 'Ear Buds', 20),
            ('FOUNDATION Fit Cream 40ml', 'Personal Care', 'Foundation', 100),
            ('GLYCERINE Bodyluxe Aloevera 50ml', 'Personal Care', 'Glycerine', 60),
            ('GLYCERINE Kapa 50ml', 'Personal Care', 'Glycerine', 80),
            ('GLYCERINE Miranda 55ml', 'Personal Care', 'Glycerine', 60),
            ('GLYCERINE Nice &Lvly 40ml', 'Personal Care', 'Glycerine', 80),
            ('GLYCERINE Nice &Lvly 65ml', 'Personal Care', 'Glycerine', 100),
            ('JELLY Afrocare 100g', 'Personal Care', 'Jelly', 70),
            ('JELLY Arimis 25ml', 'Personal Care', 'Arimis', 25),
            ('JELLY Arimis 50mls', 'Personal Care', 'Arimis', 40),
            ('JELLY Arimis 90mls', 'Personal Care', 'Arimis', 70),
            ('JELLY Arimis 200mls', 'Personal Care', 'Arimis', 130),
            ('JELLY Baby care 25g', 'Personal Care', 'Jelly', 25),
            ('JELLY Baby care 55g', 'Personal Care', 'Jelly', 50),
            ('JELLY Baby care 100g', 'Personal Care', 'Jelly', 60),
            ('JELLY Baby care 200g', 'Personal Care', 'Jelly', 120),
            ('JELLY Sawa 25ml', 'Personal Care', 'Jelly', 40),
            ('JELLY Sawa 50ml', 'Personal Care', 'Jelly', 70),
            ('JELLY Sleeping Baby 50g', 'Personal Care', 'Jelly', 60),
            ('JELLY Vaseline 25mls', 'Personal Care', 'Vaseline', 50),
            ('JELLY Vaseline 45mls', 'Personal Care', 'Vaseline', 75),
            ('JELLY Veroline 25g', 'Personal Care', 'Jelly', 20),
            ('LOTION Afro care 100mls', 'Personal Care', 'Lotion', 60),
            ('LOTION Amara 200mls', 'Personal Care', 'Lotion', 160),
            ('LOTION Amara 400mls', 'Personal Care', 'Lotion', 300),
            ('LOTION Bodyluxe 50ml', 'Personal Care', 'Lotion', 60),
            ('LOTION Fiancee 100ml', 'Personal Care', 'Lotion', 60),
            ('LOTION Nice &Lvly 200mls', 'Personal Care', 'Lotion', 200),
            ('LOTION Skala 100ml', 'Personal Care', 'Lotion', 70),
            ('LOTION Zoe 200ml', 'Personal Care', 'Lotion', 160),
            ('PADS ALWAYS', 'Personal Care', 'Pads', 80),
            ('PADS MARVEL GIRL', 'Personal Care', 'Pads', 50),
            ('PADS Softcare pcs', 'Personal Care', 'Pads', 10),
            ('PADS SOFTCARE', 'Personal Care', 'Pads', 75),
            ('PADS SUNNY GIRL', 'Personal Care', 'Pads', 70),
            ('PADS SUNNY GIRL Pcs', 'Personal Care', 'Pads', 10),
            ('PERFUME Marashi', 'Personal Care', 'Perfume', 50),
            ('PERFUME Rexona Roll-on 25ml', 'Personal Care', 'Perfume', 185),
            ('PERFUME Skala 50ml', 'Personal Care', 'Perfume', 100),
            ('TOOTH BRUSH (Colgate)', 'Personal Care', 'Tooth Brush', 50),
            ('TOOTH BRUSH - @25', 'Personal Care', 'Tooth Brush', 25),
            ('TOOTH BRUSH Kids', 'Personal Care', 'Tooth Brush', 25),
            ('TOOTH P. COLGATE 35g', 'Personal Care', 'Tooth P.', 90),
            ('TOOTH P. COLGATE 140g', 'Personal Care', 'Tooth P.', 320),
            ('TOOTH P. COLGATE 15g', 'Personal Care', 'Tooth P.', 40),
            ('TOOTH P. COLGATE Herbal 35g', 'Personal Care', 'Tooth P.', 90),
            ('TOOTH P. COLGATE Herbal 70g', 'Personal Care', 'Tooth P.', 170),
            ('TOOTH P. GUARD 140g', 'Personal Care', 'Tooth P.', 75),
            ('TOOTH P. GUARD Herbal 120g', 'Personal Care', 'Tooth P.', 75),
            ('TOOTH P. Pepsodent Herbal 65g', 'Personal Care', 'Tooth P.', 100),
            ('TOOTH P. PEPSODENT 30g', 'Personal Care', 'Tooth P.', 55),
            ('TOOTH P. PEPSODENT 65g', 'Personal Care', 'Tooth P.', 95),
            ('TOOTH P. PEPSODENT Charcoal 30g', 'Personal Care', 'Tooth P.', 80),
            ('TOOTH P. PEPSODENT Herbal 30g', 'Personal Care', 'Tooth P.', 55),
            ('TRUST CLASSIC', 'Personal Care', 'Trust', 50),
            ('WET WIPES Bella 40pcs', 'Personal Care', 'Wet Wipes', 80),
            ('WET WIPES Bella 80pcs', 'Personal Care', 'Wet Wipes', 180),
            ('WET WIPES Softcare 40pcs', 'Personal Care', 'Wet Wipes', 100),
            ('WET WIPES Softcare 80pcs', 'Personal Care', 'Wet Wipes', 180),
            ('NATURALLY FAIR', 'Personal Care', 'Naturally Fair', 100),

            # SNACKS & BISCUITS
            ('BISCUITS Anifa', 'Snacks & Biscuits', 'Biscuit', 5),
            ('BISCUITS Big Happy', 'Snacks & Biscuits', 'Biscuit', 10),
            ('BISCUITS Chocolate Tru-byte', 'Snacks & Biscuits', 'Biscuit', 10),
            ('BISCUITS Cookies', 'Snacks & Biscuits', 'Biscuit', 5),
            ('BISCUITS Family Golden 75g', 'Snacks & Biscuits', 'Biscuit', 30),
            ('BISCUITS Gingernut', 'Snacks & Biscuits', 'Biscuit', 5),
            ('BISCUITS Glucose Champ', 'Snacks & Biscuits', 'Biscuit', 10),
            ('BISCUITS Happy Happy', 'Snacks & Biscuits', 'Biscuit', 5),
            ('BISCUITS Koko', 'Snacks & Biscuits', 'Biscuit', 10),
            ('BISCUITS Marie 70g', 'Snacks & Biscuits', 'Biscuit', 30),
            ('BISCUITS Marie 85g', 'Snacks & Biscuits', 'Biscuit', 35),
            ('BISCUITS Nice', 'Snacks & Biscuits', 'Biscuit', 5),
            ('BISCUITS Nuvita Family', 'Snacks & Biscuits', 'Biscuit', 5),
            ('BISCUITS Nuvita Milk', 'Snacks & Biscuits', 'Biscuit', 5),
            ('BISCUITS Orle Glucose', 'Snacks & Biscuits', 'Biscuit', 5),
            ('BISCUITS Seema Milk', 'Snacks & Biscuits', 'Biscuit', 5),
            ('BISCUITS Tea', 'Snacks & Biscuits', 'Biscuit', 40),
            ('PEANUTS 5', 'Snacks & Biscuits', 'Peanuts', 5),
            ('PEANUTS 10', 'Snacks & Biscuits', 'Peanuts', 10),
            ('PEANUTS 20', 'Snacks & Biscuits', 'Peanuts', 20),
            ('PEANUTS Ameru', 'Snacks & Biscuits', 'Peanuts', 10),
            ('SNACKS BALLOON JOY', 'Snacks & Biscuits', 'Balloon Joy', 10),
            ('SNACKS Fun Time', 'Snacks & Biscuits', 'Fun Time', 10),
            ('SNACKS Numbers/Star', 'Snacks & Biscuits', 'General', 10),
            ('SNACKS POPCORN [Cup]', 'Snacks & Biscuits', 'Popcorn', 10),
            ('SNACKS POTATO Crisps', 'Snacks & Biscuits', 'Crisps', 20),
            ('SNACKS POTATO Crisps [cup]', 'Snacks & Biscuits', 'Crisps', 10),
            ('SNACKS POTATOES Crisps 20g', 'Snacks & Biscuits', 'Crisps', 30),
            ('SNACKS PRINCESS', 'Snacks & Biscuits', 'General', 10),
            ('SNACKS RINGOZ', 'Snacks & Biscuits', 'Ringoz', 10),
            ('SNACKS Wafers 15g', 'Snacks & Biscuits', 'Wafers', 5),
            ('SNACKS Wow', 'Snacks & Biscuits', 'Wow', 10),
            ('SNACKS Yummy', 'Snacks & Biscuits', 'Yummy', 10),
            ('CHOCOLATE Bar Cocoa Lovers', 'Snacks & Biscuits', 'Chocolate Bar', 55),
            ('CHOCOLATE Bar Dairy Milk 9g', 'Snacks & Biscuits', 'Chocolate Bar', 35),
            ('CHOCOLATE Bar Dairy Milk 35g', 'Snacks & Biscuits', 'Chocolate Bar', 140),
            ('WEETABIX', 'Snacks & Biscuits', 'Weetabix', 30),
            ('CANDY BALLGUM', 'Snacks & Biscuits', 'Candy', 1.67, 3, 5),
            ('CANDY Big G.', 'Snacks & Biscuits', 'Candy', 5),
            ('CANDY CHOCO Chocolate 3 Colors', 'Snacks & Biscuits', 'Candy', 5),
            ('CANDY CLASSIC Lollipops', 'Snacks & Biscuits', 'Candy', 10),
            ('CANDY CLOWN Mints', 'Snacks & Biscuits', 'Candy', 2.5, 2, 5),
            ('CANDY COLA', 'Snacks & Biscuits', 'Candy', 1.67, 3, 5),
            ('CANDY COOL COW Lollipops', 'Snacks & Biscuits', 'Candy', 10),
            ('CANDY Double decker', 'Snacks & Biscuits', 'Candy', 10),
            ('CANDY Fresh Pack', 'Snacks & Biscuits', 'Candy', 25),
            ('CANDY FRESH Big', 'Snacks & Biscuits', 'Candy', 10),
            ('CANDY FRESH Small', 'Snacks & Biscuits', 'Candy', 5),
            ('CANDY Gomba C. Gum', 'Snacks & Biscuits', 'Candy', 1.67, 3, 5),
            ('CANDY HARD Lollipops', 'Snacks & Biscuits', 'Candy', 10),
            ('CANDY ICE COOL Chewing Gum', 'Snacks & Biscuits', 'Candy', 1.67, 3, 5),
            ('CANDY JUICY Fruit Pack', 'Snacks & Biscuits', 'Candy', 25),
            ('CANDY JUICY FRUIT', 'Snacks & Biscuits', 'Candy', 10),
            ('CANDY KOO', 'Snacks & Biscuits', 'Candy', 1.67, 3, 5),
            ('CANDY KSL', 'Snacks & Biscuits', 'Candy', 1.67, 3, 5),
            ('CANDY LOLLIPOP-5', 'Snacks & Biscuits', 'Candy', 5),
            ('CANDY LOLLIPOP-10', 'Snacks & Biscuits', 'Candy', 10),
            ('CANDY Melon Chwg. gum', 'Snacks & Biscuits', 'Candy', 5),
            ('CANDY PAN MASALA', 'Snacks & Biscuits', 'Candy', 1.67, 3, 5),
            ('CANDY PARADISE', 'Snacks & Biscuits', 'Candy', 2.5, 2, 5),
            ('CANDY PATCO', 'Snacks & Biscuits', 'Candy', 1.67, 3, 5),
            ('CANDY PILIPILI', 'Snacks & Biscuits', 'Candy', 1.67, 3, 5),
            ('CANDY PK Big', 'Snacks & Biscuits', 'Candy', 10),
            ('CANDY PK Pack', 'Snacks & Biscuits', 'Candy', 25),
            ('CANDY PK Small', 'Snacks & Biscuits', 'Candy', 5),
            ('CANDY Spoon/Pencil', 'Snacks & Biscuits', 'Candy', 10),
            ('CANDY TAJIRI Pop', 'Snacks & Biscuits', 'Candy', 10),
            ('CANDY TINGTING Gum @1', 'Snacks & Biscuits', 'Candy', 1.67, 3, 5),
            ('CANDY TINGTING Gum @5', 'Snacks & Biscuits', 'Candy', 5),
            ('CANDY TINGTING Lollipop', 'Snacks & Biscuits', 'Candy', 10),
            ('CANDY TOFFEE', 'Snacks & Biscuits', 'Candy', 1.67, 3, 5),
            ('CANDY TOFFI BALL', 'Snacks & Biscuits', 'Candy', 5),
            ('CANDY TROPICAL Mints', 'Snacks & Biscuits', 'Candy', 3.33, 3, 10),
            ('CANDY TROPICAL Mints 1pc', 'Snacks & Biscuits', 'Candy', 5),
            ('CANDY TROPICAL Mints Lollipop', 'Snacks & Biscuits', 'Candy', 10),
            ('CANDY Twin pop', 'Snacks & Biscuits', 'Candy', 5),

            # DAIRY & BAKERY
            ('BLUEBAND 100g', 'Dairy & Bakery', 'Blueband', 80),
            ('BLUEBAND 250g', 'Dairy & Bakery', 'Blueband', 180),
            ('BLUEBAND Sachet 30g', 'Dairy & Bakery', 'Blueband', 20),
            ('BREAD 200G', 'Dairy & Bakery', 'Bread', 35),
            ('BREAD 400G', 'Dairy & Bakery', 'Bread', 70),
            ('CAKES KDF,... (10)', 'Dairy & Bakery', 'KDF', 10),
            ('CAKES MANDAZI Big', 'Dairy & Bakery', 'Mandazi', 10),
            ('CAKES MANDAZI Small', 'Dairy & Bakery', 'Mandazi', 5),
            ('CAKES NGINDURI', 'Dairy & Bakery', 'Nginduri', 5),
            ('CAKES NGUMU', 'Dairy & Bakery', 'Ngumu', 10),
            ('MILK Fresh 200ml', 'Dairy & Bakery', 'Milk', 30),
            ('MILK Fresh 500ml', 'Dairy & Bakery', 'Milk', 60),
            ('YOGHURT 250ml', 'Dairy & Bakery', 'Yoghurt', 50),
            ('YOGHURT 500ml', 'Dairy & Bakery', 'Yoghurt', 100),
            ('EGGS', 'Dairy & Bakery', 'Eggs', 17.5, 2, 35),
            ('EGGS Big 1pc', 'Dairy & Bakery', 'Eggs', 20),

            # FOOD STAPLES
            ('COOKING Fat KASUKU 250g', 'Food Staples', 'Cooking Fat', 100),
            ('COOKING Fat KASUKU 500g', 'Food Staples', 'Cooking Fat', 200),
            ('COOKING FAT 1Kg', 'Food Staples', 'Cooking Fat', 280),
            ('COOKING Oil J\'can 1/2L', 'Food Staples', 'Cooking Oil', 175),
            ('COOKING Oil J\'can 1L', 'Food Staples', 'Cooking Oil', 340),
            ('COOKING Oil J\'can Fresh fri 250ml', 'Food Staples', 'Cooking Oil', 100),
            ('COOKING OIL Salit 1L', 'Food Staples', 'Cooking Oil', 300),
            ('INDOMIE CHICKEN', 'Food Staples', 'Indomie', 45),
            ('KABRAS SUGAR 1 kg', 'Food Staples', 'Sugar', 160),
            ('SUGAR (Gulf) 1kg', 'Food Staples', 'Sugar', 200),
            ('SUGAR (Gulf) 250g', 'Food Staples', 'Sugar', 50),
            ('SUGAR (Gulf) 500g', 'Food Staples', 'Sugar', 100),
            ('NGANO AJAB 1Kg', 'Food Staples', 'Flour', 95),
            ('NGANO AJAB 2KG', 'Food Staples', 'Flour', 195),
            ('NGANO ATTA MK 1 [210] 1kg', 'Food Staples', 'Flour', 100),
            ('NGANO ATTA MK 1 [DOLA] 1kg', 'Food Staples', 'Flour', 95),
            ('NGANO ATTA MK 1[Elliots] 1kg', 'Food Staples', 'Flour', 100),
            ('NGANO BAKING Powder', 'Food Staples', 'Flour', 40),
            ('NGANO DOLA 1kg', 'Food Staples', 'Flour', 95),
            ('NGANO DOLA 2kg', 'Food Staples', 'Flour', 190),
            ('NGANO GOLDEN 2kg', 'Food Staples', 'Flour', 180),
            ('NGANO GOLGEN 1kg', 'Food Staples', 'Flour', 90),
            ('NGANO LOTUS 1kg', 'Food Staples', 'Flour', 90),
            ('NGANO LOTUS 2kg', 'Food Staples', 'Flour', 180),
            ('NGANO MOTHERS Choice 2kg', 'Food Staples', 'Flour', 170),
            ('NGANO Ndovu 1kg', 'Food Staples', 'Flour', 90),
            ('NGANO Ndovu 2kg', 'Food Staples', 'Flour', 180),
            ('NGANO RAHA 1kg', 'Food Staples', 'Flour', 95),
            ('NGANO RAHA 2kg', 'Food Staples', 'Flour', 195),
            ('RICE B 1KG', 'Food Staples', 'Rice', 120),
            ('RICE PISHORI 1kg', 'Food Staples', 'Rice', 200),
            ('SALT 1kg', 'Food Staples', 'Salt', 40),
            ('SALT 2Kg', 'Food Staples', 'Salt', 80),
            ('SALT 200g', 'Food Staples', 'Salt', 15),
            ('SALT 500g', 'Food Staples', 'Salt', 25),
            ('SAUCE CHILLI 250g', 'Food Staples', 'Seasoning', 65),
            ('SAUCE TOMATO 250g', 'Food Staples', 'Seasoning', 50),
            ('SAUCE TOMATO 400g', 'Food Staples', 'Seasoning', 65),
            ('SEASONING CURRY POWDER', 'Food Staples', 'Curry', 10),
            ('SEASONING ONGA Mchuzi mix', 'Food Staples', 'Onga', 5),
            ('SEASONING PEPPER Powder', 'Food Staples', 'Seasoning', 5),
            ('SEASONING PILAU MASALA', 'Food Staples', 'Masala', 25),
            ('SEASONING ROYCO CHILLI Cubes 4g', 'Food Staples', 'Royco', 5),
            ('SEASONING ROYCO CUBES', 'Food Staples', 'Royco', 5),
            ('SEASONING ROYCO SACHET 5', 'Food Staples', 'Royco', 5),
            ('SEASONING ROYCO SACHET 10', 'Food Staples', 'Royco', 10),
            ('SOSSI', 'Food Staples', 'Sossi', 30),
            ('SPAGHETTI Dawaat 500g', 'Food Staples', 'Spaghetti', 90),
            ('SPAGHETTI Santa Lucia 400g', 'Food Staples', 'Spaghetti', 85),
            ('UJIMIX | Wimbi 500g', 'Food Staples', 'Ujimix', 55),
            ('M.M. KARIBU 1kg', 'Food Staples', 'M.M.', 80),
            ('M.M. KARIBU 2kg', 'Food Staples', 'M.M.', 180),
            ('M.M. SATIMA 1kg', 'Food Staples', 'M.M.', 80),
            ('M.M. SOFTCORN 1kg', 'Food Staples', 'M.M.', 90),
            ('M.M. SOFTCORN 2kg', 'Food Staples', 'M.M.', 180),
            ('M.M. TAMASHA 1kg', 'Food Staples', 'M.M.', 80),
            ('FOOD COLOR', 'Food Staples', 'Seasoning', 30),
            ('TANGAWIZI Sachet', 'Food Staples', 'Seasoning', 10),

            # DRINKS
            ('Energy Drink BRAVA', 'Drinks', 'Brava', 30),
            ('Energy Drink BRAVADO', 'Drinks', 'Brava', 50),
            ('Energy Drink LEMONADE 300ml', 'Drinks', 'Energy Drink', 55),
            ('Energy Drink LEMONADE 500ml', 'Drinks', 'Energy Drink', 65),
            ('Energy Drink PREDATOR', 'Drinks', 'Predator', 70),
            ('JUICE AFIA 300ml', 'Drinks', 'Juice', 60),
            ('JUICE AFIA 500ml', 'Drinks', 'Juice', 80),
            ('JUICE HIGHLAND Cordial 0.5L', 'Drinks', 'Juice', 100),
            ('JUICE HIGHLAND Cordial 1L', 'Drinks', 'Juice', 185),
            ('JUICE HIGHLAND Cordial 2L', 'Drinks', 'Juice', 380),
            ('JUICE ICE CUBES', 'Drinks', 'Ice Cube', 10),
            ('JUICE ICE JELLY', 'Drinks', 'Ice Jelly', 10),
            ('JUICE ICE Lolly', 'Drinks', 'Lolly', 5),
            ('JUICE ICE POP', 'Drinks', 'Ice Pop', 10),
            ('JUICE MINUTE MAID 400mls', 'Drinks', 'Juice', 80),
            ('JUICE Powder Jolly Sachets', 'Drinks', 'Juice', 5),
            ('SODA 1.25L', 'Drinks', 'Soda', 140),
            ('SODA 1L', 'Drinks', 'Soda', 110),
            ('SODA 2L', 'Drinks', 'Soda', 200),
            ('SODA CLUB 300mls', 'Drinks', 'Soda', 30),
            ('SODA Glass 300ml', 'Drinks', 'Soda', 40),
            ('SODA Glass 500ml', 'Drinks', 'Soda', 60),
            ('SODA PET 350ml', 'Drinks', 'Soda', 50),
            ('SODA PET 500ml', 'Drinks', 'Soda', 80),
            ('WATER DASANI 1L', 'Drinks', 'Water', 90),
            ('WATER DASANI 500ml', 'Drinks', 'Water', 45),
            ('WATER HIGHLANDS 1L', 'Drinks', 'Water', 60),
            ('WATER HIGHLANDS 500ml', 'Drinks', 'Water', 30),
            ('WATER OXYRICH 1L', 'Drinks', 'Water', 60),
            ('WATER OXYRICH 500ml', 'Drinks', 'Water', 30),
            ('WATER QUENCHER 500ml', 'Drinks', 'Water', 30),
            ('WATER SPRINKLE 1L', 'Drinks', 'Water', 60),

            # STATIONERY
            ('ENVELOPS A4', 'Stationery', 'Envelope', 10),
            ('ENVELOPS A5', 'Stationery', 'Envelope', 5),
            ('ENVELOPS Size D', 'Stationery', 'Envelope', 5),
            ('ERASER', 'Stationery', 'Eraser', 5),
            ('Ex. BOOK A4 80pg', 'Stationery', 'Ex. Book', 60),
            ('Ex. BOOK A4 120pg', 'Stationery', 'Ex. Book', 85),
            ('Ex. BOOK A4 200pg', 'Stationery', 'Ex. Book', 130),
            ('Ex. BOOK A4 Graph 96pg', 'Stationery', 'Ex. Book', 85),
            ('Ex. BOOK A4 Plain 96pg', 'Stationery', 'Ex. Book', 85),
            ('Ex. BOOK A5 32pgs', 'Stationery', 'Ex. Book', 20),
            ('Ex. BOOK A5 48pg', 'Stationery', 'Ex. Book', 30),
            ('Ex. BOOK A5 64Pgs', 'Stationery', 'Ex. Book', 35),
            ('Ex. BOOK A5 80pgs', 'Stationery', 'Ex. Book', 40),
            ('Ex. BOOK A5 120pg', 'Stationery', 'Ex. Book', 50),
            ('Ex. BOOK A5 200Pgs', 'Stationery', 'Ex. Book', 85),
            ('Ex. BOOK A5 Graph 48pg', 'Stationery', 'Ex. Book', 30),
            ('Ex. BOOK A5 Graph 96pg', 'Stationery', 'Ex. Book', 40),
            ('Ex. BOOK A5 Plain 48pg', 'Stationery', 'Ex. Book', 30),
            ('Ex. BOOK A5 Plain 96pg', 'Stationery', 'Ex. Book', 40),
            ('Ex. BOOK COVERS A4', 'Stationery', 'Ex. Book', 25),
            ('Ex. BOOK COVERS A5', 'Stationery', 'Ex. Book', 20),
            ('Ex. COUNTER BK 3Q 288pgs', 'Stationery', 'Counter BK', 250),
            ('Ex. COUNTER BK 6Q 576pgs', 'Stationery', 'Counter BK', 450),
            ('Ex. NOTE BOOK A5 200pg', 'Stationery', 'Note Book', 110),
            ('Ex. NOTE BOOK A5 Spring', 'Stationery', 'Note Book', 65),
            ('Ex. NOTE BOOK A6', 'Stationery', 'Note Book', 60),
            ('FOUR FIGURE Math Table', 'Stationery', 'Math Table', 350),
            ('GEO. SET CAMEL', 'Stationery', 'Geo. Set', 100),
            ('GEO. SET OXFORD', 'Stationery', 'Geo. Set', 250),
            ('MANILLA PAPER', 'Stationery', 'Manilla', 40),
            ('PEN BIRO (Obama, Teepee)', 'Stationery', 'Pen', 10),
            ('PEN BIRO BIC', 'Stationery', 'Pen', 25),
            ('PEN INK (Dollar)', 'Stationery', 'Ink', 100),
            ('PEN Marker pens permanent', 'Stationery', 'Pen', 70),
            ('PEN Marking pen', 'Stationery', 'Pen', 30),
            ('PENCIL SHARPENER Plastic', 'Stationery', 'Sharpener', 5),
            ('PENCILS 2B Staedtler', 'Stationery', 'Pencil', 25),
            ('PENCILS HB Platinum', 'Stationery', 'Pencil', 10),
            ('RULER FLEX', 'Stationery', 'Ruler', 40),
            ('RULER Gel-X', 'Stationery', 'Ruler', 30),
            ('STAPLES', 'Stationery', 'Staples', 5),
            ('SUCCESS Cards', 'Stationery', 'Success Card', 50),
            ('SUCCESS Cards [Music]', 'Stationery', 'Success Card', 60),
            ('SUPER GLUE (Sparco)', 'Stationery', 'Glue', 30),
            ('SUPER GLUE (White)', 'Stationery', 'Glue', 30),
            ('TAPE Electric Globe', 'Stationery', 'Tape', 40),
            ('TAPE Electric Sunup', 'Stationery', 'Tape', 30),
            ('TAPE Masking Tape Big', 'Stationery', 'Tape', 30),
            ('TAPE Masking Tape Small', 'Stationery', 'Tape', 20),
            ('TAPES Celotape Big', 'Stationery', 'Tape', 20),
            ('TAPES Celotape Small', 'Stationery', 'Tape', 10),
            ('COLORS [Water] (Small)', 'Stationery', 'Colors', 80),
            ('COLORS [Water] Big.', 'Stationery', 'Colors', 110),
            ('COLOURED PENCIL', 'Stationery', 'Colors', 50),
            ('COLOR [OILY] TUBES', 'Stationery', 'Colors', 300),
            ('CRAYON VEDA', 'Stationery', 'Crayon', 75),
            ('CRAYONS COLOR', 'Stationery', 'Colors', 50),
            ('MODELING CRAY VEDA', 'Stationery', 'Crayon', 85),
            ('CLIP BOARD Clear', 'Stationery', 'Clip Board', 200),
            ('FILE SPRING', 'Stationery', 'File', 60),
            ('OFFICE GLUE', 'Stationery', 'Glue', 50),
            ('CALCULATOR Scientific', 'Stationery', 'Calculator', 1000),

            # MEDICINES
            ('MEDS Actal', 'Medicines', 'Actal', 20),
            ('MEDS APC [pair]', 'Medicines', 'General', 5),
            ('MEDS Cetrizine', 'Medicines', 'Cetrizine', 5),
            ('MEDS Chestcoff', 'Medicines', 'General', 20),
            ('MEDS Diclofenac Tabs', 'Medicines', 'Diclofenac', 5),
            ('MEDS ENO Sachet', 'Medicines', 'ENO', 20),
            ('MEDS Kaluma Kings Lozenges', 'Medicines', 'General', 20),
            ('MEDS Kaluma S. Tablets', 'Medicines', 'General', 10),
            ('MEDS Maramoja', 'Medicines', 'Maramoja', 10),
            ('MEDS Menthol plus', 'Medicines', 'General', 50),
            ('MEDS Menthol plus Small', 'Medicines', 'General', 30),
            ('MEDS Omeprazole', 'Medicines', 'General', 5),
            ('MEDS Panadol Advance', 'Medicines', 'Panadol', 15),
            ('MEDS Panadol Extra', 'Medicines', 'Panadol', 20),
            ('MEDS Piriton', 'Medicines', 'Cetrizine', 2.5),
            ('MEDS Sonadol', 'Medicines', 'General', 10),
            ('MEDS SONAPLAST', 'Medicines', 'General', 5),

            # CIGARETTES
            ('CIGARETTE DUNHILL Double switch', 'Cigarettes', 'Dunhill', 30),
            ('CIGARETTE PALLMALL Plus', 'Cigarettes', 'Pallmall', 10),
            ('CIGARETTE ROOSTER', 'Cigarettes', 'Rooster', 10),
            ('CIGARETTE ROTHMANS Sportsman', 'Cigarettes', 'Rothmans', 20),
            ('CIGARETTE SAFARI King 1pc', 'Cigarettes', 'Safari', 15),
            ('CIGARETTE SAFARI Kings', 'Cigarettes', 'Safari', 12.5),
            ('CIGARETTE SAFARI Menthol', 'Cigarettes', 'Safari', 12.5),
            ('CIGARETTE SAFARI Menthol 1pc', 'Cigarettes', 'Safari', 15),

            # CLEANING SUPPLIES
            ('BROOMS Big', 'Cleaning Supplies', 'Broom', 100),
            ('BROOMS Small', 'Cleaning Supplies', 'Broom', 60),
            ('BRUSH Hand Small', 'Cleaning Supplies', 'Brush', 60),
            ('SHOE BRUSH', 'Cleaning Supplies', 'Brush', 60),
            ('SCRUBBER (Steelex)', 'Cleaning Supplies', 'Scrubber', 10),
            ('SCRUBBER Scouring Brite', 'Cleaning Supplies', 'Scrubber', 10),
            ('SCRUBBER SOKONI S/wool', 'Cleaning Supplies', 'Scrubber', 10),
            ('SCRUBBER SPONGY', 'Cleaning Supplies', 'Scrubber', 30),
            ('SOAP Bleach JIK 70ml', 'Cleaning Supplies', 'Bleach', 50),
            ('SOAP Bleach JIK 250ml', 'Cleaning Supplies', 'Bleach', 200),
            ('SOAP Bleach OMO', 'Cleaning Supplies', 'Bleach', 30),
            ('SOAP Freshener DOWNY', 'Cleaning Supplies', 'Downy', 20),
            ('SOAP Freshener STARSOFT', 'Cleaning Supplies', 'Starsoft', 20),
            ('SOAP Powder ARIEL 30g', 'Cleaning Supplies', 'Soap Powder', 10),
            ('SOAP Powder ARIEL 80g', 'Cleaning Supplies', 'Soap Powder', 30),
            ('SOAP Powder ARIEL 500g', 'Cleaning Supplies', 'Soap Powder', 250),
            ('SOAP Powder NICE ONE', 'Cleaning Supplies', 'Soap Powder', 100),
            ('SOAP Powder OMO 20g', 'Cleaning Supplies', 'Soap Powder', 10),
            ('SOAP Powder OMO 75g', 'Cleaning Supplies', 'Soap Powder', 30),
            ('SOAP Powder SUNLIGHT 30g', 'Cleaning Supplies', 'Soap Powder', 10),
            ('SOAP Powder SUNLIGHT 80g', 'Cleaning Supplies', 'Soap Powder', 30),
            ('SOAP Powder Toss 20g', 'Cleaning Supplies', 'Soap Powder', 10),
            ('SOAP Powder Toss 200g', 'Cleaning Supplies', 'Soap Powder', 80),
            ('SOAP Powder Toss 500g', 'Cleaning Supplies', 'Soap Powder', 200),
            ('SERVIETTE', 'Cleaning Supplies', 'Serviette', 100),
            ('SHOE CREAM Kangaroo', 'Cleaning Supplies', 'General', 50),
            ('SHOE DYE', 'Cleaning Supplies', 'General', 50),
            ('SHOE POLISH Kiwi 15ml', 'Cleaning Supplies', 'General', 60),
            ('SHOE POLISH Kiwi 40ml', 'Cleaning Supplies', 'General', 150),
            ('SHOE POLISH Kiwi 80g/100ml', 'Cleaning Supplies', 'General', 260),
            ('SPIRIT 300ml (Methylated)', 'Cleaning Supplies', 'Spirit', 60),
            ('SPIRIT 500ml (Methylated)', 'Cleaning Supplies', 'Spirit', 100),

            # CLOTHING & ACCESSORIES
            ('SOCKS MEN (Ankle)', 'Clothing & Access.', 'Socks', 50),
            ('SOCKS MEN (Shin)', 'Clothing & Access.', 'Socks', 50),
            ('HANDKERCHIEF #30', 'Clothing & Access.', 'Handkerchief', 30),
            ('HANDKERCHIEF #20', 'Clothing & Access.', 'Handkerchief', 20),
            ('HANDKERCHIEF #50', 'Clothing & Access.', 'Handkerchief', 50),
            ('EARRINGS #20', 'Clothing & Access.', 'Earrings', 20),
            ('EARRINGS #50', 'Clothing & Access.', 'Earrings', 50),
            ('HAIR BAND Small (Christina)', 'Clothing & Access.', 'Hair Band', 50),
            ('HAIR Cap Bonnet', 'Clothing & Access.', 'Hair Cap', 130),
            ('HAIR Cap Stocking', 'Clothing & Access.', 'Hair Cap', 50),

            # KITCHENWARE
            ('GRATERS', 'Kitchenware', 'Grater', 50),
            ('LUNCH BOX', 'Kitchenware', 'Lunch Box', 50),
            ('LUNCH BUSKET', 'Kitchenware', 'Lunch Busket', 100),
            ('SIEVES Medium', 'Kitchenware', 'Sieve', 20),
            ('SIEVES Small', 'Kitchenware', 'Sieve', 15),
            ('TUMBLERS cup 4 Oz', 'Kitchenware', 'Tumbler', 70),
            ('TUMBLERS cup 5 Oz', 'Kitchenware', 'Tumbler', 80),
            ('TUMBLERS cup 6 Oz', 'Kitchenware', 'Tumbler', 110),
            ('TUMBLERS cup 300mls', 'Kitchenware', 'Tumbler', 120),
            ('TUMBLERS cup 500mls Pack', 'Kitchenware', 'Tumbler', 150),
            ('TUMBLERS cup 500mls Pcs', 'Kitchenware', 'Tumbler', 10),
            ('MWIKO (Wooden)', 'Kitchenware', 'Mwiko', 50),
            ('FEEDING BOTTLES Big', 'Kitchenware', 'Feeding Bottle', 100),
            ('FEEDING BOTTLES Small', 'Kitchenware', 'Feeding Bottle', 70),

            # TOOLS & SEWING
            ('CROCHETS', 'Tools & Sewing', 'Crochet', 60),
            ('KNITTING PINS', 'Tools & Sewing', 'Knitting', 175),
            ('KNITTING WOOL', 'Tools & Sewing', 'Wool', 70),
            ('KNITTING WOOL Thick', 'Tools & Sewing', 'Wool', 120),
            ('PEGS Pcs', 'Tools & Sewing', 'General', 1.67, 3, 5),
            ('PEGS Pkts', 'Tools & Sewing', 'General', 20),
            ('ROPES Broad Colored', 'Tools & Sewing', 'Ropes', 150),
            ('ROPES Narrow Colored', 'Tools & Sewing', 'Ropes', 130),
            ('ROPES Nylon Pleated (Mbuzi)', 'Tools & Sewing', 'Ropes', 40),
            ('ROPES Sisal (Mbuzi)', 'Tools & Sewing', 'Ropes', 25),
            ('ROPES Sisal Broad White', 'Tools & Sewing', 'Ropes', 60),
            ('SACK NEEDLES', 'Tools & Sewing', 'Sack Needle', 25),
            ('SACK NYLON Thread Twine', 'Tools & Sewing', 'Thread', 100),
            ('SACKS Chania 100kg', 'Tools & Sewing', 'General', 65),
            ('SACKS Green 90kg', 'Tools & Sewing', 'General', 50),
            ('SEWING Needles Long (Size 3.5)', 'Tools & Sewing', 'Needle', 10),
            ('SEWING Needles Short (No.1 &6)', 'Tools & Sewing', 'Needle', 5),
            ('SEWING Thread 200Y', 'Tools & Sewing', 'Thread', 15),
            ('SEWING Thread 400Y', 'Tools & Sewing', 'Thread', 20),
            ('SHOE LACES Flat Long', 'Tools & Sewing', 'General', 25),
            ('SHOE LACES Flat Short', 'Tools & Sewing', 'General', 20),
            ('SHOE LACES Round Long', 'Tools & Sewing', 'General', 40),
            ('SHOE LACES Round Long (White)', 'Tools & Sewing', 'General', 50),
            ('SHOE LACES Round Short', 'Tools & Sewing', 'General', 30),
            ('SHOE THREAD', 'Tools & Sewing', 'Thread', 2.5, 2, 5),
            ('MACHINE OIL', 'Tools & Sewing', 'Machine OIL', 50),
            ('CLOTH LINE (Wire)', 'Tools & Sewing', 'Cloth Line', 200),
            ('SPEAKER Cable (45M)', 'Tools & Sewing', 'Speaker Cable', 10),

            # MISCELLANEOUS
            ('MISCELLANEOUS - Other', 'Miscellaneous', 'Miscellaneous', 20),
            ('MISCELLANEOUS - Phone Charging', 'Miscellaneous', 'Phone Charging', 10),
            ('MISCELLANEOUS - Pressure', 'Miscellaneous', 'Pressure', 10),
            ('MISCELLANEOUS Jerry Can 10L', 'Miscellaneous', 'Jerry Can', 40),
            ('MISCELLANEOUS Jerry Can 20L', 'Miscellaneous', 'Jerry Can', 70),
            ('MODELING CRAY VEDA', 'Stationery', 'Crayon', 85),
            ('INSECTICIDE POWDER', 'Household', 'Insecticide', 100),
            ('MOSQUITO Coil', 'Household', 'Mosquito Coil', 20),

            # HAIR ACCESSORIES (Additional Personal Care)
            ('HAIR BRAIDS', 'Personal Care', 'Hair', 70),
            ('HAIR BRAIDS Angel', 'Personal Care', 'Hair', 75),
            ('HAIR Buds #10', 'Personal Care', 'Hair', 10),
            ('HAIR Buds #30', 'Personal Care', 'Hair', 30),
            ('HAIR Buds #50', 'Personal Care', 'Hair', 50),
            ('HAIR CLIPS Butterfly', 'Personal Care', 'Hair', 5),
            ('HAIR COMB (Plastic)', 'Personal Care', 'Hair', 20),
            ('HAIR DYE DEXE', 'Personal Care', 'Hair', 50),
            ('HAIR FOOD BAMSI 50g', 'Personal Care', 'Hair', 60),
            ('HAIR GEL MOVIT 80g', 'Personal Care', 'Hair', 60),
            ('HAIR GEL MOVIT 150g', 'Personal Care', 'Hair', 150),
            ('HAIR JOLLY COMBS', 'Personal Care', 'Hair', 20),
            ('HAIR Moulding Gel Wax BAMSI 80g', 'Personal Care', 'Hair', 150),
            ('HAIR SHOWER Caps', 'Personal Care', 'Hair', 50),
            ('HAIR STYLING Gel Sodaso 80g', 'Personal Care', 'Hair', 100),

            # ADDITIONAL SOAPS (Cleaning / Personal Care)
            ('SOAP Bar MENENGAI 1kg (Bar)', 'Cleaning Supplies', 'Soap Bar', 240),
            ('SOAP Bar MENENGAI 1kg (Tab)', 'Cleaning Supplies', 'Soap Bar', 50),
            ('SOAP Bar MENENGAI 800g (Bar)', 'Cleaning Supplies', 'Soap Bar', 180),
            ('SOAP Bar MENENGAI 800g (Tab)', 'Cleaning Supplies', 'Soap Bar', 40),
            ('SOAP Bar META (Bar)', 'Cleaning Supplies', 'Soap Bar', 185),
            ('SOAP Bar META (Tab) 1/5', 'Cleaning Supplies', 'Soap Bar', 40),
            ('SOAP Bar META (Tab) 1/6', 'Cleaning Supplies', 'Soap Bar', 35),
            ('SOAP Tab Cussons 75g', 'Personal Care', 'Soap Tab', 85),
            ('SOAP Tab Cussons 125g', 'Personal Care', 'Soap Tab', 90),
            ('SOAP Tab Dettol 60g', 'Personal Care', 'Soap Tab', 40),
            ('SOAP Tab Geisha 90g', 'Personal Care', 'Soap Tab', 55),
            ('SOAP Tab Geisha 125g', 'Personal Care', 'Soap Tab', 80),
            ('SOAP Tab Geisha 200g', 'Personal Care', 'Soap Tab', 130),
            ('SOAP Tab SAWA 125g', 'Personal Care', 'Soap Tab', 50),
            ('SOAP Tab SAWA 225g', 'Personal Care', 'Soap Tab', 85),
            ('SOAP Tab SUNLIGHT 50g', 'Personal Care', 'Soap Tab', 35),
            ('SOAP Tab SUNLIGHT 80g', 'Personal Care', 'Soap Tab', 35),
            ('SOAP Tab USHINDI 175g', 'Personal Care', 'Soap Tab', 50),
            ('SOAP Tab WHITE WASH 175g', 'Personal Care', 'Soap Tab', 50),

            # MORE STATIONERY (Filling out the list)
            ('Ex. BOOK A4 80pg', 'Stationery', 'Ex. Book', 60),
            ('Ex. BOOK A4 120pg', 'Stationery', 'Ex. Book', 85),
            ('Ex. BOOK A4 200pg', 'Stationery', 'Ex. Book', 130),
            ('Ex. BOOK A4 Graph 96pg', 'Stationery', 'Ex. Book', 85),
            ('Ex. BOOK A4 Plain 96pg', 'Stationery', 'Ex. Book', 85),
            ('Ex. BOOK A5 32pgs', 'Stationery', 'Ex. Book', 20),
            ('Ex. BOOK A5 48pg', 'Stationery', 'Ex. Book', 30),
            ('Ex. BOOK A5 64Pgs', 'Stationery', 'Ex. Book', 35),
            ('Ex. BOOK A5 80pgs', 'Stationery', 'Ex. Book', 40),
            ('Ex. BOOK A5 120pg', 'Stationery', 'Ex. Book', 50),
            ('Ex. BOOK A5 200Pgs', 'Stationery', 'Ex. Book', 85),
            ('Ex. BOOK A5 Graph 48pg', 'Stationery', 'Ex. Book', 30),
            ('Ex. BOOK A5 Graph 96pg', 'Stationery', 'Ex. Book', 40),
            ('Ex. BOOK A5 Plain 48pg', 'Stationery', 'Ex. Book', 30),
            ('Ex. BOOK A5 Plain 96pg', 'Stationery', 'Ex. Book', 40),
            ('Ex. BOOK COVERS A4', 'Stationery', 'Ex. Book', 25),
            ('Ex. BOOK COVERS A5', 'Stationery', 'Ex. Book', 20),
            ('Ex. COUNTER BK 3Q 288pgs', 'Stationery', 'Counter BK', 250),
            ('Ex. COUNTER BK 6Q 576pgs', 'Stationery', 'Counter BK', 450),
            ('Ex. NOTE BOOK A5 200pg', 'Stationery', 'Note Book', 110),
            ('Ex. NOTE BOOK A5 Spring', 'Stationery', 'Note Book', 65),
            ('Ex. NOTE BOOK A6', 'Stationery', 'Note Book', 60),
            ('GEO. SET CAMEL', 'Stationery', 'Geo. Set', 100),
            ('GEO. SET OXFORD', 'Stationery', 'Geo. Set', 250),

            # BULBS & TORCHES (Filling out)
            ('TORCH Solar/Recharge [TH-5133] Small', 'Household', 'Torch', 250),
            ('TORCH Solar/Recharge [TH5155] Big', 'Household', 'Torch', 350),
            ('TORCHES Batt-LED [ST-5098A] Med.', 'Household', 'Torch', 100),
            ('TORCHES Batt-LED [ST-9992] Med.', 'Household', 'Torch', 110),
            ('TORCHES Small', 'Household', 'Torch', 30),
            ('BULB Rechargeable 40w', 'Household', 'Bulb', 450),
            ('BULB Rechargeable 50w', 'Household', 'Bulb', 550),

            # ADDITIONAL CANDY (Filling out)
            ('CANDY PATCO', 'Snacks & Biscuits', 'Candy', 1.67, 3, 5),
            ('CANDY PILIPILI', 'Snacks & Biscuits', 'Candy', 1.67, 3, 5),
            ('CANDY PATCO Small', 'Snacks & Biscuits', 'Candy', 1.67, 3, 5),
            ('CANDY PILIPILI Small', 'Snacks & Biscuits', 'Candy', 1.67, 3, 5),
            ('CANDY PK Big', 'Snacks & Biscuits', 'Candy', 10),
            ('CANDY PK Pack', 'Snacks & Biscuits', 'Candy', 25),
            ('CANDY PK Small', 'Snacks & Biscuits', 'Candy', 5),
            ('CANDY Spoon/Pencil', 'Snacks & Biscuits', 'Candy', 10),
            ('CANDY TAJIRI Pop', 'Snacks & Biscuits', 'Candy', 10),
            ('CANDY TINGTING Gum @1', 'Snacks & Biscuits', 'Candy', 1.67, 3, 5),
            ('CANDY TINGTING Gum @5', 'Snacks & Biscuits', 'Candy', 5),
            ('CANDY TINGTING Lollipop', 'Snacks & Biscuits', 'Candy', 10),
            ('CANDY TOFFEE', 'Snacks & Biscuits', 'Candy', 1.67, 3, 5),
            ('CANDY TOFFI BALL', 'Snacks & Biscuits', 'Candy', 5),
            ('CANDY TROPICAL Mints', 'Snacks & Biscuits', 'Candy', 3.33, 3, 10),
            ('CANDY TROPICAL Mints 1pc', 'Snacks & Biscuits', 'Candy', 5),
            ('CANDY TROPICAL Mints Lollipop', 'Snacks & Biscuits', 'Candy', 10),
            ('CANDY Twin pop', 'Snacks & Biscuits', 'Candy', 5),

            # OTHERS
            ('TOWELS #30', 'Clothing & Access.', 'General', 30),
            ('TOWELS #50', 'Clothing & Access.', 'General', 50),
            ('SCISSORS', 'Stationery', 'General', 30),
            ('SUCCESS Cards', 'Stationery', 'Success Card', 50),
            ('SUCCESS Cards [Music]', 'Stationery', 'Success Card', 60),
            ('TISSUE MFALME', 'Personal Care', 'General', 25),
            ('TISSUE NALLA Jumbo', 'Personal Care', 'General', 100),
            ('TISSUE NEPTUNE', 'Personal Care', 'General', 40),
            ('TISSUE PEKEE', 'Personal Care', 'General', 30),
            ('TISSUE PEKEE Jumbo', 'Personal Care', 'General', 100),
            ('TISSUE PEKEE Poa', 'Personal Care', 'General', 25),
            ('TISSUE TOILEX', 'Personal Care', 'General', 40),

            # FINAL BATCH TO REACH 500+
            ('CANDY BALLGUM Small', 'Snacks & Biscuits', 'Candy', 1.67, 3, 5),
            ('CANDY CHOCO 3 Colors Small', 'Snacks & Biscuits', 'Candy', 5),
            ('CANDY CLASSIC Lollipops Big', 'Snacks & Biscuits', 'Candy', 10),
            ('CANDY CLOWN Mints Pack', 'Snacks & Biscuits', 'Candy', 50),
            ('CANDY COLA Big', 'Snacks & Biscuits', 'Candy', 5),
            ('CANDY COOL COW Lollipops Big', 'Snacks & Biscuits', 'Candy', 10),
            ('CANDY FRESH Pack Big', 'Snacks & Biscuits', 'Candy', 25),
            ('CANDY Gomba C. Gum Pack', 'Snacks & Biscuits', 'Candy', 25),
            ('CANDY ICE COOL Chewing Gum Pack', 'Snacks & Biscuits', 'Candy', 25),
            ('CANDY JUICY Fruit Pack Big', 'Snacks & Biscuits', 'Candy', 25),
            ('CANDY KOO Pack', 'Snacks & Biscuits', 'Candy', 25),
            ('CANDY KSL Pack', 'Snacks & Biscuits', 'Candy', 25),
            ('CANDY Melon Chwg. gum Pack', 'Snacks & Biscuits', 'Candy', 25),
            ('CANDY PAN MASALA Pack', 'Snacks & Biscuits', 'Candy', 25),
            ('CANDY PARADISE Pack', 'Snacks & Biscuits', 'Candy', 50),
            ('CANDY PATCO Pack', 'Snacks & Biscuits', 'Candy', 25),
            ('CANDY PILIPILI Pack', 'Snacks & Biscuits', 'Candy', 25),
            ('CANDY PK Pack Big', 'Snacks & Biscuits', 'Candy', 25),
            ('CANDY TINGTING Gum Pack', 'Snacks & Biscuits', 'Candy', 50),
            ('CANDY TOFFEE Pack', 'Snacks & Biscuits', 'Candy', 25),
            ('CANDY TROPICAL Mints Pack', 'Snacks & Biscuits', 'Candy', 100),
            ('BISCUITS Anifa Big', 'Snacks & Biscuits', 'Biscuit', 10),
            ('BISCUITS Big Happy Big', 'Snacks & Biscuits', 'Biscuit', 20),
            ('BISCUITS Cookies Big', 'Snacks & Biscuits', 'Biscuit', 10),
            ('BISCUITS Gingernut Big', 'Snacks & Biscuits', 'Biscuit', 10),
            ('BISCUITS Happy Happy Big', 'Snacks & Biscuits', 'Biscuit', 10),
            ('BISCUITS Koko Big', 'Snacks & Biscuits', 'Biscuit', 20),
            ('BISCUITS Nice Big', 'Snacks & Biscuits', 'Biscuit', 10),
            ('BISCUITS Nuvita Family Big', 'Snacks & Biscuits', 'Biscuit', 10),
            ('BISCUITS Nuvita Milk Big', 'Snacks & Biscuits', 'Biscuit', 10),
            ('BISCUITS Orle Glucose Big', 'Snacks & Biscuits', 'Biscuit', 10),
            ('BISCUITS Seema Milk Big', 'Snacks & Biscuits', 'Biscuit', 10),
            ('MISC - Phone Charging Service', 'Miscellaneous', 'Phone Charging', 10),
            ('MISC - Water Pressure Service', 'Miscellaneous', 'Pressure', 10),
        ]

        # 3. Processing loop
        for i, p_data in enumerate(items_data):
            name = p_data[0]
            cat_name = p_data[1]
            sub_hint = p_data[2]
            price = Decimal(str(p_data[3]))
            sku = "JM-" + re.sub(r'[^A-Z0-9]', '', name.upper())[:12] + str(i).zfill(3)
            
            bundle_qty = p_data[4] if len(p_data) > 4 else 1
            bundle_price = Decimal(str(p_data[5])) if len(p_data) > 5 else Decimal('0.00')

            # Find or create subcategory
            sub = subcats.get(f"{cat_name}:{sub_hint}") or subcats.get(f"{cat_name}:General")
            
            try:
                Product.objects.update_or_create(
                    name=name,
                    defaults={
                        'subcategory': sub,
                        'base_unit_price': price,
                        'cost_price': price * Decimal('0.85'),
                        'sku': sku,
                        'image': cats[cat_name].icon,
                        'created_by': admin,
                        'stock_qty': Decimal('100'),
                        'bundle_pricing_enabled': (bundle_qty > 1),
                        'bundle_qty': bundle_qty,
                        'bundle_price': bundle_price,
                        'allow_single_sale': True,
                        'single_unit_price': price
                    }
                )
                if (i+1) % 50 == 0:
                    self.stdout.write(f"Processed {i+1} items...")
            except IntegrityError:
                # Fallback to unique name if collision occurs
                Product.objects.update_or_create(
                    sku=sku,
                    defaults={
                        'name': f"{name} ({sku})",
                        'subcategory': sub,
                        'base_unit_price': price,
                        'cost_price': price * Decimal('0.85'),
                        'image': cats[cat_name].icon,
                        'created_by': admin,
                        'stock_qty': Decimal('100'),
                        'bundle_pricing_enabled': (bundle_qty > 1),
                        'bundle_qty': bundle_qty,
                        'bundle_price': bundle_price,
                        'allow_single_sale': True,
                        'single_unit_price': price
                    }
                )

        self.stdout.write(self.style.SUCCESS(f"Successfully seeded {len(items_data)} items for Jimmy Mini Mart."))
