# Generated by Django 6.0.2 on 2026-04-22 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hamper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('barcode', models.CharField(blank=True, default='', max_length=50)),
                ('image', models.CharField(default='🎁', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Fixed composite selling price', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HamperComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('use_split', models.BooleanField(default=False, help_text='Use split unit instead of whole base unit')),
                ('hamper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='promotions.hamper')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hamper_components', to='catalogue.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('promo_type', models.CharField(choices=[('bogof', 'Buy One Get One Free'), ('multi_unit', 'Multi-Unit Deal'), ('pct_discount', 'Percentage Discount'), ('fixed_discount', 'Fixed Amount Off')], max_length=15)),
                ('buy_qty', models.IntegerField(blank=True, help_text='Buy N items', null=True)),
                ('free_qty', models.IntegerField(blank=True, help_text='Get M free', null=True)),
                ('deal_qty', models.IntegerField(blank=True, help_text='e.g., 3 for KES 5', null=True)),
                ('deal_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='catalogue.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='catalogue.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
