# Generated by Django 6.0.2 on 2026-04-22 10:10

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Current on-hand quantity for this batch', max_digits=12)),
                ('received_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('quarantined', 'Quarantined'), ('disposed', 'Disposed')], default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['expiry_date', 'received_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(default='📦', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Sub-categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=50, unique=True)),
                ('barcode', models.CharField(blank=True, default='', max_length=50)),
                ('image', models.CharField(default='📦', max_length=10)),
                ('base_unit_label', models.CharField(default='Unit', max_length=30)),
                ('base_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('split_enabled', models.BooleanField(default=False, help_text='Can this product be sold in pieces?')),
                ('split_unit_label', models.CharField(blank=True, default='Piece', max_length=30)),
                ('split_unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per piece — set freely by admin, NEVER derived from base price', max_digits=12, null=True)),
                ('pieces_per_base', models.IntegerField(default=1, help_text='Reference cut size per base unit (e.g., 8 pieces per bar)')),
                ('split_min_qty', models.IntegerField(default=1, help_text='Minimum pieces per transaction')),
                ('split_inventory_mode', models.CharField(choices=[('FIXED_CUT', 'Fixed Cut'), ('OPEN_CUT', 'Open Cut')], default='FIXED_CUT', max_length=10)),
                ('weight_sell_enabled', models.BooleanField(default=False, help_text='Sell by weight')),
                ('weight_unit', models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('litre', 'Litres'), ('ml', 'Millilitres')], default='kg', max_length=10)),
                ('price_per_weight_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Selling price per weight unit (e.g., KES 150/kg)', max_digits=12, null=True)),
                ('stock_in_weight_unit', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Current on-hand stock in weight units (e.g., 25.750 kg)', max_digits=12)),
                ('weight_sell_mode', models.CharField(choices=[('BY_WEIGHT', 'By Weight (cashier types kg)'), ('BY_CASH', 'By Cash (cashier types KES)')], default='BY_WEIGHT', max_length=10)),
                ('min_weight_increment', models.DecimalField(decimal_places=3, default=Decimal('0.050'), help_text='Smallest sellable weight (e.g., 0.050 kg = 50g)', max_digits=12)),
                ('reorder_threshold_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('bunch_enabled', models.BooleanField(default=False)),
                ('bunch_qty', models.IntegerField(default=1, help_text='Quantity in one bunch')),
                ('bunch_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price for the bunch', max_digits=12, null=True)),
                ('single_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price if sold individually (fallback when qty not exact bunch multiple)', max_digits=12, null=True)),
                ('stock_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='On-hand stock in base units', max_digits=12)),
                ('reorder_threshold', models.IntegerField(default=5)),
                ('reorder_qty', models.IntegerField(default=10)),
                ('desired_margin_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Target gross margin as %', max_digits=5, null=True)),
                ('desired_margin_kes', models.DecimalField(blank=True, decimal_places=2, help_text='Target gross margin in KES per base unit', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
