# Generated by Django 5.1.15 on 2026-04-26 10:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='bunch_enabled',
            new_name='bundle_pricing_enabled',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bunch_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bunch_qty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='single_price',
        ),
        migrations.AddField(
            model_name='product',
            name='allow_single_sale',
            field=models.BooleanField(default=False, help_text='Allow selling < 1 bundle'),
        ),
        migrations.AddField(
            model_name='product',
            name='bundle_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per bundle in KES', max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='bundle_qty',
            field=models.PositiveIntegerField(default=1, help_text='Base units per bundle. Must be >= 2 when enabled.'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_unit_label',
            field=models.CharField(default='unit', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='single_unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per base unit when selling singles', max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='units_per_purchase',
            field=models.PositiveIntegerField(default=1, help_text='1 = no conversion'),
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('SALE', 'Sale'), ('GRN', 'Goods Received Note'), ('ADJUSTMENT', 'Manual Adjustment'), ('VOID', 'Void / Refund')], max_length=20)),
                ('qty_delta', models.IntegerField(help_text='Signed integer in base units (- for sales, + for receipts)')),
                ('bundle_qty_sold', models.PositiveIntegerField(blank=True, help_text='Number of bundles in a SALE entry', null=True)),
                ('bundle_size_snapshot', models.PositiveIntegerField(blank=True, help_text='Bundle Qty value at time of sale', null=True)),
                ('bundle_price_snapshot', models.DecimalField(blank=True, decimal_places=2, help_text='Bundle Price at time of sale', max_digits=12, null=True)),
                ('is_singles_sale', models.BooleanField(default=False, help_text='True if this sale line used per-unit pricing')),
                ('unit_label_snapshot', models.CharField(blank=True, default='', max_length=30)),
                ('purchase_unit_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('purchase_unit_label_snapshot', models.CharField(blank=True, default='', max_length=30)),
                ('reference_id', models.CharField(blank=True, default='', help_text='Sale ID, GRN ID, etc.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='catalogue.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
