# Generated by Django 5.1.15 on 2026-04-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_rename_bunch_enabled_product_bundle_pricing_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockledger',
            name='batch_snapshot',
            field=models.CharField(blank=True, default='', help_text='Batch Number snapshot', max_length=100),
        ),
    ]
