# Generated by Django 5.1.15 on 2026-04-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_tag_alter_category_options_category_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='barcode',
        ),
    ]
