# Generated by Django 5.1.15 on 2026-04-26 14:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_stockledger_batch_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_kadogo',
            field=models.BooleanField(default=False, help_text='Enable cutting whole units into fragments'),
        ),
        migrations.AddField(
            model_name='product',
            name='whole_unit_stock',
            field=models.IntegerField(default=0, help_text='Count of uncut whole units available'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='cut_action_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='fragment_size_snapshot',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='pool',
            field=models.CharField(choices=[('WHOLE', 'Whole Unit Pool'), ('FRAGMENT', 'Fragment Pool')], default='WHOLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='entry_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('GRN', 'Goods Received Note'), ('ADJUSTMENT', 'Manual Adjustment'), ('VOID', 'Void / Refund'), ('CUT', 'Stock Cutting Action')], max_length=20),
        ),
        migrations.CreateModel(
            name='FragmentSize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('fragment_count', models.PositiveIntegerField(help_text='Number of fragments per whole unit (e.g., 7 for a 7-piece cut)')),
                ('fragment_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('fragment_pool', models.IntegerField(default=0, help_text='Current available fragments of this size')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragment_sizes', to='catalogue.product')),
            ],
            options={
                'unique_together': {('product', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CutAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('whole_units_cut', models.PositiveIntegerField(default=1)),
                ('fragments_added', models.PositiveIntegerField()),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.CharField(choices=[('SALE', 'Sale Triggered'), ('MANUAL', 'Manual Pre-cut')], default='MANUAL', max_length=10)),
                ('sale_reference', models.CharField(blank=True, default='', max_length=100)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.batch')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cut_actions', to='catalogue.product')),
                ('fragment_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.fragmentsize')),
            ],
        ),
        migrations.AddField(
            model_name='stockledger',
            name='fragment_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.fragmentsize'),
        ),
    ]
