# Generated by Django 5.1.15 on 2026-04-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_product_is_kadogo_product_whole_unit_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='whole_unit_label',
            field=models.CharField(default='Bar', help_text='Label for the whole unit (e.g., Bar, Packet)', max_length=30),
        ),
    ]
