# Generated by Django 6.0.2 on 2026-04-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_rename_category_to_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='types',
            field=models.JSONField(blank=True, default=list, help_text="Product-specific types, e.g. ['Ragged', 'Straight', 'Skinny']"),
        ),
    ]
