# Generated by Django 5.1.15 on 2026-06-03 09:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_increase_cost_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_qty',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='On-hand stock in base units', max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='qty_delta',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Signed decimal in base units (- for sales, + for receipts)', max_digits=12),
        ),
    ]
