# Generated by Django 5.2.4 on 2025-07-30 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'July 2025 Payroll'", max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pay_date', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Paid', 'Paid')], default='Draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_entries', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payroll.payrollperiod')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ALLOWANCE', 'Allowance'), ('DEDUCTION', 'Deduction')], max_length=10)),
                ('name', models.CharField(help_text="e.g., 'SHA Contribution', 'Loan Repayment', 'Travel Bonus'", max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_adjustments', to=settings.AUTH_USER_MODEL)),
                ('payroll_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payroll.payrollentry')),
            ],
        ),
    ]
