# Generated by Django 5.2.4 on 2025-09-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_payrollperiod_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollentry',
            name='reward_points_redeemed',
            field=models.PositiveIntegerField(default=0, help_text='Number of waiter reward points redeemed as cash in this payroll'),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='reward_points_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cash value of redeemed points', max_digits=10),
        ),
    ]
