# Generated by Django 5.1.15 on 2026-04-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payrollentry_reward_points_redeemed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollentry',
            name='reward_points_redeemed',
        ),
        migrations.RemoveField(
            model_name='payrollentry',
            name='reward_points_value',
        ),
    ]
