# Generated by Django 6.0.2 on 2026-04-22 10:10

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_initial'),
        ('promotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkedSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_identifier', models.CharField(blank=True, default='', max_length=50)),
                ('items', models.JSONField(default=list)),
                ('parked_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parked_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-parked_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=20, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('split', 'Split (Cash + M-Pesa)'), ('credit', 'Credit / Tab')], default='cash', max_length=10)),
                ('cash_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cash_tendered', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('change_due', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mpesa_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mpesa_phone', models.CharField(blank=True, default='', max_length=15)),
                ('mpesa_reference', models.CharField(blank=True, default='', max_length=100)),
                ('mpesa_stk_checkout_id', models.CharField(blank=True, default='', max_length=100)),
                ('credit_customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('credit_due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('voided', 'Voided'), ('pending_payment', 'Pending Payment')], default='complete', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('void_reason', models.TextField(blank=True, default='')),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('sell_mode', models.CharField(choices=[('whole', 'Whole Unit'), ('split', 'Split / Pieces'), ('weight', 'Weight'), ('bunch', 'Bunch'), ('hamper', 'Hamper')], default='whole', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('weight_value', models.DecimalField(blank=True, decimal_places=3, help_text='Weight sold (e.g., 1.333 kg)', max_digits=12, null=True)),
                ('weight_unit', models.CharField(blank=True, default='', max_length=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('is_free_item', models.BooleanField(default=False, help_text='BOGOF free items')),
                ('cost_price_at_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.batch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='catalogue.product')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.promotion')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='pos.sale')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
