# Generated by Django 5.1.15 on 2026-04-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salelineitem',
            name='bundle_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='salelineitem',
            name='bundle_size_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salelineitem',
            name='is_singles_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salelineitem',
            name='sell_mode',
            field=models.CharField(choices=[('whole', 'Whole Unit'), ('split', 'Split / Pieces'), ('weight', 'Weight'), ('bundle', 'Bundle'), ('single', 'Singles'), ('hamper', 'Hamper')], default='whole', max_length=10),
        ),
    ]
