# Generated by Django 5.1.15 on 2026-04-05 10:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_transaction_coupon_discount_coupon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkedSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_identifier', models.CharField(blank=True, help_text='Optional name or tag for the parked sale', max_length=50)),
                ('items', models.JSONField(default=list)),
                ('parked_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parked_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-parked_at'],
            },
        ),
    ]
