# Generated by Django 5.1.15 on 2026-05-21 07:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_cancellationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashHandover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cash_amount', models.DecimalField(decimal_places=2, help_text='Cash Counted', max_digits=12)),
                ('mpesa_amount', models.DecimalField(decimal_places=2, help_text='M-Pesa Counted', max_digits=12)),
                ('in_shop_expenses', models.DecimalField(decimal_places=2, help_text='Expenses & Procurement', max_digits=12)),
                ('total_sales', models.DecimalField(decimal_places=2, help_text='Expected Total Sales', max_digits=12)),
                ('variance', models.DecimalField(decimal_places=2, help_text='Shortage / Surplus', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_confirmed', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
