# Generated by Django 5.1.15 on 2026-05-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_cashhandover'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashhandover',
            name='shift_end',
            field=models.DateTimeField(blank=True, help_text='End of shift period', null=True),
        ),
        migrations.AddField(
            model_name='cashhandover',
            name='shift_start',
            field=models.DateTimeField(blank=True, help_text='Start of shift period', null=True),
        ),
    ]
