# Generated by Django 5.1.15 on 2026-04-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_transaction_void_reason_transaction_voided_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='split_payments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
