# Generated by Django 5.1.15 on 2026-04-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_transaction_split_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tip_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total tips from price increases', max_digits=10),
        ),
    ]
