# Generated by Django 5.1.15 on 2026-06-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_cashhandover_shift_end_cashhandover_shift_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salelineitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
