# Generated by Django 5.1.15 on 2026-06-03 23:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_alter_salelineitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashhandover',
            name='ad_hoc_purchases',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cash used for AD HOC purchases', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cashhandover',
            name='in_shop_expenses',
            field=models.DecimalField(decimal_places=2, help_text='In-Shop Expenses', max_digits=12),
        ),
    ]
